### ISSUE TITLE
Plugin failed to load

### ISSUE THREAD

**Issue by rndeon** [petko10/rhythmbox-plugin-playlists-import-export#10]
I'm on ubuntu 14.04, RB 3.0.2.
I ran RB in debug mode and got this when trying to click the plugin checkbox from the menu. 

> Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
 AttributeError: 'DynamicImporter' object has no attribute 'find_spec'
 During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ryan/.local/share/rhythmbox/plugins/playlists_ie/playlists_ie.py", line 15, in <module>
    from gi.repository import Gio, GObject, Peas, RB, GConf, Gtk
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GConf, introspection typelib not found
(rhythmbox:3227): libpeas-WARNING **: Error loading plugin 'playlists_ie'

Any ideas?
Thanks!

**Comment by petko10** [comment]
Do you have gconf and python gconf installed ? (I'm not sure what the exact package names in ubuntu are, but it should be something like libgconf-python)

**Comment by oscarpax** [comment]
I have the same problem with Ubuntu 16.04, RB 3.3. I have many gconf packages installed as well as libgconf-2-4 and python-gconf. Thanks.

**Comment by rndeon** [comment]
I just checked, I do have python-gconf installed. with libgconf-2-4

**Comment by Martanus** [comment]
Same Problem also with Ubuntu 16.04 RB 3.3

**Comment by petko10** [comment]
It looks like some library isn't installed. I cannot reproduce the issue, so I'm having trouble figuring it out. Try checking if you have all the packages for Gio, GObject, Peas, RB, GConf, Gtk (libraries and python bindings. And I'll ping @fossfreedom if he has any idea.

**Comment by fossfreedom** [comment]
probably gir1.2-gconf-2.0 needs to be installed?

**Comment by Martanus** [comment]
Thanks! That's it. 

> sudo apt install gir1.2-gconf-2.0

**Comment by oscarpax** [comment]
Worked for me too! Thanks!

**Comment by rndeon** [comment]
Yup, that's it. Thank you
