### ISSUE TITLE
Rhythmbox 3.4.1 compatibility

### ISSUE THREAD

**Issue by latach** [petko10/rhythmbox-plugin-playlists-import-export#13]
Could you please fix the plugin so that it works with Rhythmbox 3.4.1?

**Comment by petko10** [comment]
It works on my computer (RB 3.4.1) . Can you give some more information (errors, etc.) about how it's not working for you.

**Comment by latach** [comment]
Oh thank you for replying. I have installed the plugin as instructed. 

But when I try to turn it on from the plugins window, it turns gray (please see screenshot).

I'm running Ubuntu 17.04, RB 3.4.1.

![screenshot - 20170910 - 21 19 25](https://user-images.githubusercontent.com/21196400/30252623-eeb665b2-966d-11e7-8975-71b116f0a1df.png)

**Comment by latach** [comment]
And here is another snapshot on Ubuntu LTS 16.04 (Virtual Machine):

![screenshot - 20170911 - 13 46 58](https://user-images.githubusercontent.com/21196400/30275079-00cc45e8-96f8-11e7-8e45-e9468cc86991.png)

**Comment by petko10** [comment]
Can you run rhythmbox from the command line and copy/paste the output after RB starts (there should be some error messages related to the extension).

**Comment by latach** [comment]
![screenshot - 20170911 - 16 04 52](https://user-images.githubusercontent.com/21196400/30281768-33deb494-970b-11e7-9682-2adf39379b3d.png)

**Comment by joegnis** [comment]
Exact same error here on `Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-92-generic x86_64)`

I'm using

- GNOME Shell 3.18.5
- Rhythmbox 3.3

**Comment by joegnis** [comment]
OK, after a quick [research](https://bugs.launchpad.net/ubuntu/+source/gobject-introspection/+bug/979266), I installed `gir1.2-gconf-2.0` and problem was solved.

**Comment by petko10** [comment]
I suspected it's dependency related, as most of the bugs here are (the extension doesn't do dependency checks, which is my fault, but I don't really have the time to implement them, and I don't even know how possible it is to do that for more distributions). @joegnis thank you for resolving this one, I'm closing it now. @latach , if you keep having problems running the plugin I'll reopen, but I guess installing gir1.2-gconf-2.0 will fix the issue.

**Comment by petko10** [comment]
Actually GConf isn't really needed. I reviewed the old issues now, and I'd started using GSettings in 2014, but forgot to remove the dependecy. Will patch that now.

**Comment by latach** [comment]
I confirm that installing this lib fixes the issue. Thank you both.
