### ISSUE TITLE
adding single playlist update to tools

### ISSUE THREAD

**Issue by lachlan-00** [petko10/rhythmbox-plugin-playlists-import-export#14]
I'm just adding a menu option to update the currently view playlist.

Would you accept a pull after i'm done?

**Comment by petko10** [comment]
Yup, no problem. Thanks for contributing.

**Comment by lachlan-00** [comment]
Do you want to keep RB2 support? I don't think there are any distributions left on the old versions.

**Comment by petko10** [comment]
If it's not in the way somehow I would rather keep it. You're thinking cleanup or you want to do something that's not RB2 compatible?

**Comment by lachlan-00** [comment]
I've done the manual import so I was cleaning up code as well on top.
I'll pull an older version of Debian to test rb2 as well then pull request when I've tested both.

Thanks
