### ISSUE TITLE
Selecting Plugin Preferences Crashes RB

### ISSUE THREAD

**Issue by RyanS027** [petko10/rhythmbox-plugin-playlists-import-export#19]
When entering RB Preferences and going to Plugins tab, selecting Preferences for the Playlists import/export plugin crashes RB. Is there any alternative to this plugin? Or potential workarounds?

RB version: 3.4.4
Linux Mint 20.1 Cinnamon 4.8.6

**Comment by v-ko** [comment]
Can you run RB from terminal and post the output? It's possible you're missing a library or something like that.

**Comment by RyanS027** [comment]
Thanks for the reply @petko10  terminal run results below.

```
** (rhythmbox:263374): WARNING **: 09:30:10.472: Error initializing Python Plugin Loader: PyGObject initialization failed
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

** (rhythmbox:263374): WARNING **: 09:30:10.472: Please check the installation of all the Python related packages required by libpeas and try again

(rhythmbox:263374): libpeas-WARNING **: 09:30:10.472: Loader 'python3' is not a valid PeasPluginLoader instance

(rhythmbox:263374): Rhythmbox-WARNING **: 09:30:10.576: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon.MediaKeys was not provided by any .service files
```

**Comment by v-ko** [comment]
As per the error you're missing the `gi` module. Try installing it using `sudo apt-get install python3-gi` or similar (I don't know what your distro is)

**Comment by RyanS027** [comment]
Looks like it's already installed? Restarted PC after install attempt and RB is still crashing. Running RB from terminal as user gives the same error log from above.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.36.0-1).
The following packages were automatically installed and are no longer required:
  libllvm10 libllvm10:i386 libnvidia-compute-455:i386
  libnvidia-decode-455:i386 libnvidia-encode-455:i386 libnvidia-fbc1-455:i386
  libnvidia-gl-455:i386 libnvidia-ifr1-455:i386 linux-headers-5.4.0-59
  linux-headers-5.4.0-59-generic linux-headers-5.4.0-60
  linux-headers-5.4.0-60-generic linux-headers-5.4.0-62
  linux-headers-5.4.0-62-generic linux-image-5.4.0-58-generic
  linux-image-5.4.0-59-generic linux-image-5.4.0-60-generic
  linux-image-5.4.0-62-generic linux-modules-5.4.0-58-generic
  linux-modules-5.4.0-59-generic linux-modules-5.4.0-60-generic
  linux-modules-5.4.0-62-generic linux-modules-extra-5.4.0-58-generic
  linux-modules-extra-5.4.0-59-generic linux-modules-extra-5.4.0-60-generic
  linux-modules-extra-5.4.0-62-generic nvidia-kernel-common-455
  nvidia-kernel-source-455 nvidia-utils-455 python3-pychromecast
  xserver-xorg-video-nvidia-455
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by v-ko** [comment]
Try installing `python-gi` for good measure (no PC restart, just RB should be enough). And if that doesn't work - check that you can import `gi` from the python console. That means typing `python` in the terminal and then typing `import gi`. Btw I just saw you mentioned OS version and RB version. They seem recent enough.
As a last note: haw did you install the extension? Can you try reinstalling it from this repo?

**Comment by RyanS027** [comment]
import gi command results below. Looks like there's conda environment confusion?
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
```

Trying to install directly to conda stalls/loops with the following:
```
$conda install -c conda-forge pygobject
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
```

**Comment by v-ko** [comment]
Well I'd restore my python to the OS default and alias the Anaconda interpreter to something else (if I still want to have it handy). I couldn't find a quick fix for installing pygobject in conda.

**Comment by RyanS027** [comment]
@petko10 just to close the loop after finally getting to this, unfortunately Python3 environment is now default (not conda) with RB still crashing upon plugin preference selection or import/export playlist selection 

```
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```


FWIW, running RB from terminal still does return an error but don't know if it's relative at this point:
```
(rhythmbox:6600): Rhythmbox-WARNING **: 17:14:02.457: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: 
The name org.gnome.SettingsDaemon.MediaKeys was not provided by any .service files
```

**Comment by v-ko** [comment]
@RyanS027 I believe the warning is irrelevant, the extension should be working. Do re-open the issue if there's still a problem.
